---

- hosts: localhost
  tasks:
    - name: debug version
      debug:
        var: ansible_version

    - name: debug msg for loop
      debug:
        msg: "{{ ansible_date_time.iso8601 }}"
      loop:
      until: True == False
      retries: 1000
      delay: 5
